/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthActivateAccountRouteImport } from './routes/_auth/activate-account'
import { Route as DashboardFormsIndexRouteImport } from './routes/_dashboard/forms/index'
import { Route as DashboardFormsPersonaMoralIndexRouteImport } from './routes/_dashboard/forms/persona-moral/index'
import { Route as DashboardFormsPersonaFisicaIndexRouteImport } from './routes/_dashboard/forms/persona-fisica/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivateAccountRoute = AuthActivateAccountRouteImport.update({
  id: '/activate-account',
  path: '/activate-account',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardFormsIndexRoute = DashboardFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFormsPersonaMoralIndexRoute =
  DashboardFormsPersonaMoralIndexRouteImport.update({
    id: '/forms/persona-moral/',
    path: '/forms/persona-moral/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormsPersonaFisicaIndexRoute =
  DashboardFormsPersonaFisicaIndexRouteImport.update({
    id: '/forms/persona-fisica/',
    path: '/forms/persona-fisica/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-account': typeof AuthActivateAccountRoute
  '/login': typeof AuthLoginRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/forms': typeof DashboardFormsIndexRoute
  '/forms/persona-fisica': typeof DashboardFormsPersonaFisicaIndexRoute
  '/forms/persona-moral': typeof DashboardFormsPersonaMoralIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-account': typeof AuthActivateAccountRoute
  '/login': typeof AuthLoginRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/forms': typeof DashboardFormsIndexRoute
  '/forms/persona-fisica': typeof DashboardFormsPersonaFisicaIndexRoute
  '/forms/persona-moral': typeof DashboardFormsPersonaMoralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/activate-account': typeof AuthActivateAccountRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/forms/': typeof DashboardFormsIndexRoute
  '/_dashboard/forms/persona-fisica/': typeof DashboardFormsPersonaFisicaIndexRoute
  '/_dashboard/forms/persona-moral/': typeof DashboardFormsPersonaMoralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-account'
    | '/login'
    | '/home'
    | '/settings'
    | '/forms'
    | '/forms/persona-fisica'
    | '/forms/persona-moral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-account'
    | '/login'
    | '/home'
    | '/settings'
    | '/forms'
    | '/forms/persona-fisica'
    | '/forms/persona-moral'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/activate-account'
    | '/_auth/login'
    | '/_dashboard/home'
    | '/_dashboard/settings'
    | '/_dashboard/forms/'
    | '/_dashboard/forms/persona-fisica/'
    | '/_dashboard/forms/persona-moral/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activate-account': {
      id: '/_auth/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof AuthActivateAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/forms/': {
      id: '/_dashboard/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof DashboardFormsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forms/persona-moral/': {
      id: '/_dashboard/forms/persona-moral/'
      path: '/forms/persona-moral'
      fullPath: '/forms/persona-moral'
      preLoaderRoute: typeof DashboardFormsPersonaMoralIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forms/persona-fisica/': {
      id: '/_dashboard/forms/persona-fisica/'
      path: '/forms/persona-fisica'
      fullPath: '/forms/persona-fisica'
      preLoaderRoute: typeof DashboardFormsPersonaFisicaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthActivateAccountRoute: typeof AuthActivateAccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivateAccountRoute: AuthActivateAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute
  DashboardFormsPersonaFisicaIndexRoute: typeof DashboardFormsPersonaFisicaIndexRoute
  DashboardFormsPersonaMoralIndexRoute: typeof DashboardFormsPersonaMoralIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute,
  DashboardFormsPersonaFisicaIndexRoute: DashboardFormsPersonaFisicaIndexRoute,
  DashboardFormsPersonaMoralIndexRoute: DashboardFormsPersonaMoralIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
